version: '3'
services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.50.1
    shm_size: 1gb
    ipc: host
    cap_add:
      - SYS_ADMIN
    networks:
      - backend
    environment:
      - MAGENTO_BASE_URL
      - MAGENTO_ADMIN_USERNAME
      - MAGENTO_ADMIN_PASSWORD
      - CI
    volumes:
      - ../../../:/tmp/module
networks:
  backend:
