<?php
/* @var LastPageRemember $block */

use Mbissonho\RememberAdminLastPage\Block\Adminhtml\LastPageRemember;
use Mbissonho\RememberAdminLastPage\Helper\Data;
$helper = $this->helper(Data::class);
?>
<?php if($helper->isActive()): ?>
<script>
    require([], function () {
        sessionStorage.setItem('mbissonho-last-admin-page-accessed', '<?= /* @noEscape */ json_encode($block->getPathData(), JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_TAG | JSON_HEX_AMP) ?>')
    });
</script>
<?php endif; ?>

